# docker run -d --rm --name mongo -p 27018:27017 -v mongodbdata:/data/db mongo:4.4.5

version: "3.8"

services: 
    mongo:
        image: mongo:4.4.5
        container_name: mongo
        ports: 
            - 27018:27017
        volumes: 
            - mongodbdata:/data/db
volumes: 
    mongodbdata:
